const LOADING_MEMES = 'LOADING_MEMES'
const SET_MEMES = 'SET_MEMES'
const GEN_RANDOM_MEME = 'GEN_RANDOM_MEME'
const CLEAR_MEME = 'CLEAR_MEME'
// const START_MEME_POST_REQUEST = 'START_MEME_POST_REQUEST'
const ADD_SAVED_MEME = 'ADD_SAVED_MEME'
const LOADING_SAVED_MEMES = 'LOADING_SAVED_MEMES'
const SET_SAVED_MEMES = 'SET_SAVED_MEMES'

const LOADING_GIFS = 'LOADING_GIFS'
const SET_QUERIED_GIFS = 'SET_QUERIED_GIFS'
const GEN_RANDOM_GIF = 'GEN_RANDOM_GIF'
const SET_QUERY_INPUT = 'SET_QUERY_INPUT'
const CLEAR_GIF = 'CLEAR_GIF'
const ADD_SAVED_GIF = 'ADD_SAVED_GIF'
const LOADING_SAVED_GIFS = 'LOADING_SAVED_GIFS'
const SET_SAVED_GIFS = 'SET_SAVED_GIFS'

const LOADING_CAPTIONS = 'LOADING_CAPTIONS'
const SET_CAPTIONS = 'SET_CAPTIONS'
const GEN_RANDOM_CAPTIONS_ALL = 'GEN_RANDOM_CAPTIONS_ALL'
const GEN_RANDOM_CAPTIONS_PG = 'GEN_RANDOM_CAPTIONS_PG'
const GEN_RANDOM_CAPTIONS_R = 'GEN_RANDOM_CAPTIONS_R'
const SET_CHOSEN_CAPTION = 'SET_CHOSEN_CAPTION'
const CLEAR_CHOSEN_CAPTION = 'CLEAR_CHOSEN_CAPTION'
const CLEAR_CAPTIONS = 'CLEAR_CAPTIONS'
const SET_CAPTION_INPUT = 'SET_CAPTION_INPUT'

const SET_USER = 'SET_USER'

export {
    LOADING_MEMES,
    SET_MEMES,
    GEN_RANDOM_MEME,
    CLEAR_MEME,
    // START_MEME_POST_REQUEST,
    ADD_SAVED_MEME,
    LOADING_SAVED_MEMES,
    SET_SAVED_MEMES,

    LOADING_GIFS,
    SET_QUERIED_GIFS,
    GEN_RANDOM_GIF,
    SET_QUERY_INPUT,
    CLEAR_GIF,
    ADD_SAVED_GIF,
    LOADING_SAVED_GIFS,
    SET_SAVED_GIFS,

    LOADING_CAPTIONS,
    SET_CAPTIONS,
    GEN_RANDOM_CAPTIONS_ALL,
    GEN_RANDOM_CAPTIONS_PG,
    GEN_RANDOM_CAPTIONS_R,
    SET_CHOSEN_CAPTION,
    CLEAR_CHOSEN_CAPTION,
    CLEAR_CAPTIONS,
    SET_CAPTION_INPUT,

    SET_USER
}