const SET_MEMES = 'SET_MEMES'
const GEN_RANDOM_MEME = 'GEN_RANDOM_MEME'
const SET_CAPTIONS = 'SET_CAPTIONS'
const GEN_RANDOM_CAPTIONS_ALL = 'GEN_RANDOM_CAPTIONS_ALL'
const GEN_RANDOM_CAPTIONS_PG = 'GEN_RANDOM_CAPTIONS_PG'
const GEN_RANDOM_CAPTIONS_R = 'GEN_RANDOM_CAPTIONS_R'
const SET_CHOSEN_CAPTION = 'SET_CHOSEN_CAPTION'
const CLEAR_CHOSEN_CAPTION = 'CLEAR_CHOSEN_CAPTION'

export {
    SET_MEMES,
    GEN_RANDOM_MEME,
    SET_CAPTIONS,
    GEN_RANDOM_CAPTIONS_ALL,
    GEN_RANDOM_CAPTIONS_PG,
    GEN_RANDOM_CAPTIONS_R,
    SET_CHOSEN_CAPTION,
    CLEAR_CHOSEN_CAPTION
}